#!/bin/bash
set -e
cd "$(dirname "$0")"

v="$(node -v|head -c3)"
if [ "$v" != v7. -a "$v" != v8. -a "$v" != v9. ]; then
  echo "this project requires node v7+ but the one on your \$PATH is $(node -v)"
  exit 1
fi

stat -c '%n: %s bytes' apl.js

#todo: echo -n 'var aplTests = ' ; node test/collectdoctests.js

echo doctests; test/collectdoctests.js | test/rundoctests.js
echo examples; examples/test
echo ok
